version: "3.1"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  moe:
    restart: on-failure
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=fb.paperscut.com
networks:
  default:
    external:
      name: nginx-proxy
