version: "3.1"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/certs
      - ./ssl:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  cs361:
    image: flashspys/nginx-static
    container_name: cs361-website 
    ports:
      - 3000:80
    volumes: 
      - ./build:/static
    restart: on-failure
    environment:
      - VIRTUAL_HOST=cs361.cs.uic.edu
networks:
  default:
    external:
      name: nginx-proxy
