name: Publish course website

on: 
  push:
    branches:
      - main
jobs:
  docusaurus:
    runs-on: ubuntu-18.04
    steps:
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        # this key is restricted to only rsync to the course website directory
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - run: echo -e "|1|Oorna+8eFr+D/PU+OmEhWsSwQNs=|yMk5e99S/ZdGwvN2Yoy2ETkVFJw= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmn6kY7stPr09RmQ8hCA/ZcGrQ+Z3Ijxf4JnBP3D1uTPOZDmYF1xGkRtEn9MGneYXtAN4TPIKzhObvgnAAxyr/dqamlReApmjFPEgq/hAfRfjfxZ1JYNowVdyOwgcesnREZuiQOD4bDo905nyF8OJAKERe4X/VGIvSXwMOx+my5urT4k/bHbsDOy1AbP/vnz3hS4R2tCgqvKP24hekBc0cBYVGHWXL2K7rg7dcXj12gwn9kmPHv1WwzDVZfY/n6X7CmNnjwEYbxVg9vepvD6vb8z2FzhJrhUdB8RVPZHnZ8csROaGbzTLJucG/DZ3M+bj/LHS7h+5RYtGzjBGaZg7D" >> $HOME/.ssh/known_hosts
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        yarn install --frozen-lockfile
        yarn build
    - run: >
        rsync -e "ssh -v" -avz build/ mghas2@cs361.cs.uic.edu:
